[pytest]

; To avoid '@pytest.mark.asyncio' on every testing function
asyncio_mode = auto

; Force all test functions to share one SINGLE event loop (the engine that makes async operations work)
asyncio_default_fixture_loop_scope = session
asyncio_default_test_loop_scope = session