"""add cascade delete to user-board roles table

Revision ID: 5a5505167419
Revises: be7bdd607c5e
Create Date: 2026-09-09 09:55:12.604674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a5505167419'
down_revision: Union[str, Sequence[str], None] = 'be7bdd607c5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_board_roles_board_id_fkey'), 'user_board_roles', type_='foreignkey')
    op.drop_constraint(op.f('user_board_roles_user_id_fkey'), 'user_board_roles', type_='foreignkey')
    op.create_foreign_key(None, 'user_board_roles', 'boards', ['board_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_board_roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_board_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_board_roles', type_='foreignkey')
    op.create_foreign_key(op.f('user_board_roles_user_id_fkey'), 'user_board_roles', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('user_board_roles_board_id_fkey'), 'user_board_roles', 'boards', ['board_id'], ['id'])
    # ### end Alembic commands ###
