"""add cascade delete to board_columns and tasks foreign keys

Revision ID: be7bdd607c5e
Revises: 91f53a48e99e
Create Date: 2026-09-08 19:22:39.295867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be7bdd607c5e'
down_revision: Union[str, Sequence[str], None] = '91f53a48e99e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('board_columns_board_id_fkey'), 'board_columns', type_='foreignkey')
    op.create_foreign_key(None, 'board_columns', 'boards', ['board_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tasks_column_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'board_columns', ['column_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_column_id_fkey'), 'tasks', 'board_columns', ['column_id'], ['id'])
    op.drop_constraint(None, 'board_columns', type_='foreignkey')
    op.create_foreign_key(op.f('board_columns_board_id_fkey'), 'board_columns', 'boards', ['board_id'], ['id'])
    # ### end Alembic commands ###
